server:
  port: 8080

spring:
  application:
    name: book-service


author-service:
  url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


